### ISSUE TITLE
Last Millennium Problem [FTB Infinity Evolved 1.7.10]

### ISSUE THREAD

**Issue by bazzonatale47** [rwtema/extrautilities_old_issues#1193]
Hi everyone :)

I have a huge problem with the Last Millennium dimension.

Today I was playing Minecraft when I decided to modify a little thing on my smelting system.

I went home, I entered in the Last Millennium (with the portal, not with other methods) and I saw that the dimension has been resetted.

But I noticed that all my things on that dimension were still working, because the smelting system was running perfectly.

I noticed also that before this "reset", if i clicked on the portal to came back home, it spawned me at the initial game spawn, not on the other portal; now, if I click on the portal, it spawns me on the home portal, exactly as it should be.

If you can help me I will be really really really grateful, because losing all my things that were in that dimension is so much frustrating!

Thanks

**Comment by ghost** [comment]
Are you on a server? Maybe the dimension number was changed, so your stuff is in another dimension.

**Comment by bazzonatale47** [comment]
@charlesbevans 
No, I'm not. 
But after some researches I think that the portal changed the spawn number, exactly as you say.

**Comment by ghost** [comment]
Are you good to restore your old last millennium or do you need help?

**Comment by bazzonatale47** [comment]
@charlesbevans 
Yesterday I tried to look into some Extra Utilities files but, for me, it's a huge mess. So, yes. I need a lot of help.

**Comment by ghost** [comment]
@bazzonatale47 First things first. What modpack/launcher are you using, if any? Do you know how to get to the folders with the configs and saves?

**Comment by bazzonatale47** [comment]
@charlesbevans 
I'm actually using the FTB Infinity Reloaded modpack, installed from Curse launcher. About these folders I think I can get to them through: "Curse folder" > Instances > FTB Infinity Evolved > Config/Saves/... but I'm not so sure about tihis.

Can we write each other in another way, like E-Mail or something like this? Because this bug report is basically a conversation between us. Thank you

**Comment by ghost** [comment]
You can try to message me on Curse at Blue_Wanderer, but I'd like the fix on file for others. Besides, I've been having a weird problem with my account that no one's been able to solve and you may not be able to contact me there right now.
1. I can't find a FTB Infinity Reloaded pack on either the Curse launcher or the FTB site. I'm going to assume you meant FTB Infinity Lite. It's the only FTB Infinity pack that's not 1.7.10. If it's the wrong pack, still follow the instructions the result will likely be the same.
2. Remove everything of value from your Last Millennium, including yourself.
3. Go in to your instance folder and go into the saves folder. Back up the save for your world, it should have the name you see when loading it. If everything goes south you can just restore the folder. You can also duplicate the folder with a different name and it will be loadable.
4. Go into the folder for your saved game. We are interested in the folders that start with DIM. You should have:
- DIM-1 (The Nether)
- DIM-9999 (The Last Millennium)
- DIM-11325 (Quantum Quarry dimension)
- DIM1 (The End)
- DIM6 (Aroma1997's Dimensional World)
If your LM dimension was changed, you should have one more dimension. What you want to do is delete the DIM-9999 folder. Then rename the extra dimension folder to DIM-9999.
5. Load and test. If something goes wrong reply. I'm around right now.
Good luck.

**Comment by bazzonatale47** [comment]
@charlesbevans 
No, I'm actually playing on 1.7.10, the Infinity Evolved ;)

Abaut the problem, I can't find the DIM-9999, but after some researches on internet I found that the LM is DIM-112, so I assume that you mean DIM-112.

I have a lot of dimensions, maybe i can put a screenshot attached to this reply.

DIMs with -MYST are there because I made a lot of Mystcraft Dimensions, so these are OK.

The other DIMs are there because I created many many RFTools dimensions, so I don't know which dimension is the duplicated one.
![dim files screenshot](https://cloud.githubusercontent.com/assets/24831707/21639228/3f9ab0fa-d26f-11e6-9c22-731367a56fb0.png)

**Comment by ghost** [comment]
[For future reference, please state the modpack and version when you post a problem, especially when it's not the current version. It's important information for troubleshooting.]
I installed FTB Infinity Evolved 2.6.0 and started a new game. The DIM_MYST* you know, DIM-1 & DIM1 are vanilla. DIMs -7, -19, -37, -38, -39, -100, -112 are generated with a new game. (I also tried Skyblock, which didn't generate -7.) My game also generated -34 and -42. The Last Millennium is -112 in this pack.
This leaves 13, 15, and 16, which are probably RFTools dimensions. You should be able to check using the RFTools dialer.
To be sure, we're going to check. Since you're on 1.7.10 you can install Anti-ID Conflict. Click on the Inf. Ev. picture in the launcher. In the upper right corner of the window is a button with an ellipsis (...). Select that and choose "Profile Options." Uncheck "Locked" and select "OKAY." (You can relock it when you're done.) Now choose "Get More Content." Make sure you're searching "Mods" and search for "conflict". The second choice is Anti-ID conflict. When you mouse over it, the install button will appear. Install it and run the game. A new folder will appear in the instance, "config\AntiIDConflict". Go to "\Dimensions". Open "\occupiedIDs.txt". All of the dimension owners should be listed.
Let me know if you find anything useful. Paste the \occupiedIDs file if you need to.

**Comment by ghost** [comment]
Rereading your initial post, I want to offer another possible solution while you're at it. Perhaps you're in the same dimension in a different place. In JourneyMap, there's an actions button. Inside you can choose to Auto-Map everything. What this will do is regenerate your map of all the already generated chunks. You can try zooming out and scrolling around to see if you can find your previous LM base. (If you have any old screenshots or savegames, you can also try getting coordinates from there.)

**Comment by bazzonatale47** [comment]
@charlesbevans 
Yes, 13, 15 and 16 are RFTools Dimensions.

Thanks to you I found my LM Base with the 2nd method, scrolling around the map i found a previously-loaded chunk. I also installed the Anti-ID Conflict, but in that file the Last Millennium wasn't present.

Again thank you very much.

**Comment by ghost** [comment]
You're welcome. I'm glad I could help.
