### ISSUE TITLE
[Bug]Increasing Amount of power generators/users on reloading world.

### ISSUE THREAD

**Issue by Pieterv24** [rwtema/extrautilities_old_issues#1337]
Type: Supposed Bug
MC Version: 1.10.2
Mod Version: 1.3.0
Modpack: Direwolf20 v1.6.2

(This is about grid power btw)
Each time I reload my world, the amount of power generators and users I actually have in the world get's added to the amount it thought there were in the world previously.

For example: If I have 2 solar panels in the world the next time I reload the power manager sais there are 4.
When I reload my world again it sais there are 6, next time it sais 8 and that goes on.

Also when I create a new world.
For some reason when I look at the power manager eventhough I've not placed any gridpower devices sais I've the same amount of devices as I have in the before mentioned world.
But the power being the max power generated is some absurd high number I can't firgure out where it comes from.

Restarting Minecraft seems to reset everything but reloading causes the issue to reappear.

I suspect the cause of the issue to be the way data about grid power machines is stored.

**Comment by Lethann** [comment]
Came here with this same problem. I don't always shut minecraft off because it takes so long to load and eventually it became so bad the entire grid shut down. 

Tried the solution of total shutdown of minecraft. It fixed how much was generated but it didnt' fix how much was being used.  See Screenshot: 
![2017-03-13_15 19 35](https://cloud.githubusercontent.com/assets/25929754/23873590/97284a78-0800-11e7-8fb5-8c8789f7e6a3.png)

All I have that's using grid power is a single mining upgrade to pump water into a tank.

Tried pulling out all things that generated or used Grid Power and while it did go down the 10 GP for the upgrade being removed it still had that ridiculous about being used. It will take 12 creative mills to try and cover this bug.

Is there any slash command to reset/refresh the GP grid??

**Comment by TrueKuehli** [comment]
Edit: 
The following report was a bit of my stupidity for not being able to read Version numbers. So yeah just for anybody finding this post, this bug had been fixed a long time ago. Some Modpacks still use older versions of XU, however, especially those, that have their recipes heavyly tweaked, as it would be too much work for their respective authors to update each mod with their additions and tweak them (this would also require heavy testing in each version on their side so yeah). Anyway, I don't know if updating fixes the Grid Power Bug, otherwise just follow the instructions given in this post here, they worked for me at least (https://github.com/scalda/FoolCraft/issues/216#issuecomment-292752767).

Old Post:
```
Okay, this bug still seems to occur and it's seriously a weird one, for my main Survival World it just started out of nothing after a couple weeks of playing. Basically all my machines are jammed up, but the Power Manager shows the right numbers of GP being generated / used, while the Machine Numbers increase each time I start the world (each time adding the current amount of existing machines to the count). Looking at GP Items in my Inventory or GP Blocks in the World shows a much bigger power use, that seems to be independant of the Block-Multiplicator (While my machines were at 6x Multiplicator the Power Usage was at about 50.2x). The Power Generation shown by looking at GP Blocks seems unaffected though. A temporary fix seems to be to delete the data/XU2SaveData.dat file in your save to reset the GP Usage, although it seems to not affect the numbers in the Power Manager. This fix only lasts until you log off, though. 

Edit: Okay, now after I've deleted my XU2SaveData and reloading the World a couple of times the previously correct GP Numbers in the Power Manager are also off, this bug seriously confuses me. There seems to be a fix (https://github.com/scalda/FoolCraft/issues/216#issuecomment-292752767) involving some NBT Editing and picking up all GP Machines and placing them back down, will have to try that later.
```
