### ISSUE TITLE
[1.7.2] TE report

### ISSUE THREAD

**Issue by MrSapient** [rwtema/extrautilities_old_issues#140]
http://pastebin.com/bmAjFihc

i know your one mod with only two TE will not do much .. but when i have 10 mods all doing it then it starts to add up.

**Comment by rwtema** [comment]
Uggh, what a waste of time. Spamming the chat log is probably a bigger drain on system resources than what it's complaining about. Do you know which mod is doing this, because they should damn well be identifying their output properly and not just using system.out.print, especially if they're going to be nitpicking other peoples code.
