### ISSUE TITLE
Mechaical User missing

### ISSUE THREAD

**Issue by tony453** [rwtema/extrautilities_old_issues#1463]
cant find it in the list of craftable items =x was it disabled or something? i remember using it in foolcraft

**Comment by mcdodge34** [comment]
Its disabled because of a world corrupting bug that will make you constantly crash if you accidentally stand in front of a mechanical user set to entity mode, so far I've read it was caused by a mod called Minecraft Comes Alive, if you can live without the new villagers around the villages, you can take that mod out of your pack and enable the mechanical user again in exutils2 config file (search for user that's the name of it in the config), but be careful, I'm not 100% sure its totally fixed, so backup your world before trying to play with the mechanical user again and avoid standing in front of it.

**Comment by calloatti** [comment]
Had to restore a backup because of this. (No MCA mod). **Do not use Mechanical Users!**

**Comment by tony453** [comment]
ah i see, found that disabled line in the config file and re-enabled it lol and if i happen to step infront of it ill just use mcedit to change where i spawn :)
