### ISSUE TITLE
question for u 

### ISSUE THREAD

**Issue by CharCharthemonkey** [rwtema/extrautilities_old_issues#1702]
in the recipe for the chicken ring can there be a way to add certian chickens for said recipe or no? i ask cause using a mod that replaces vanilla chickens makes it impossible to craft the ring so figured i probably should ask if its possible to add it in? plz and ty

**Comment by CharCharthemonkey** [comment]
(forgot to mention name of mod for chickens) is animania (oopsy)

**Comment by hron84** [comment]
@CharCharthemonkey This is not a forum, this is an issue tracker. Please consider this platform as it is, if you have any issues with your game, please describe it and also please add Minecraft, Forge and ExtraUtilities version number to your issue to help developers track down what's happening.

For questions, please use the dedicated channel, like the [CurseForge project page](https://minecraft.curseforge.com/projects/extra-utilities) for XU2.

And the answer for your question is go and try it out yourself. As I guess, leghorn chickens should work because they replacing vanilla chickens but mostly only in the model. If it is not working, please report it in a separate issue, naming Animania and ExtraUtilities version. For workaround, Animania has a configuration option to disable replacing vanilla animals, so in the case its chicken not works in the recipe, you can always be able to spawn a vanilla chicken *after* changing this option. I hope it helps.

**Comment by CharCharthemonkey** [comment]
i found the solution for the ring question i just turned off the chicken riung and everything works again so yay
