### ISSUE TITLE
bug regarding GP efficiency

### ISSUE THREAD

**Issue by tom89194** [rwtema/extrautilities_old_issues#1847]
Forge 1.12.2  14.23.1.2600
Extra Utils 2 1.7.2
Direwolf 20 pack (on server) version 1.7.1

The efficiency loss of the water mills seems to be different from what is reported in JEI
JEI
0-64           0%
64-128     33%
128-512   60%
512-1024 90%

What I actually get (with and without other types of mills)
Mills      /Eff loss        /GP generated 
   9           20%      114.66
  18          35%       186.66
  27          40%       258.66
  36          47%       304.92
  45          56%       319.5
  54          61%       333.72
  64          66%       350.08
 
Since JEI says 60% loss at 512 I would have expected to see less than 60% loss until reaching 512 GP from water mills.... not before.

Great mod, thanks for the hard work.

**Comment by Kzorith** [comment]
When you are looking at your numbers, are you looking at what the mills can generate or what they are generating.  Because, in my testing, the loss is based on what they can generate.  80 solar panels (80 GP possible, 80 GP generated) are fine, 160 (160 GP possible, 80 + (33% of 80) or 133.33 GP generated) sees the 33% loss on production above 80 GP, 161 or more sees the 50% loss of production above 160 GP in addition to the 33% loss above 80 GP. (80 + (33% of 80) + (50% of 1)) = 133.83 GP

The loss is independent of other sources.  So if you have a dragon mill producing 500 GP, that won't affect your water mills.

**Comment by tom89194** [comment]
Your formula is spot on for solar panels.... BUT using the formula on water mills
64 + 64(67%) + 16(40%) = 113.28 for 9 water mills is close to what I got
64 + 64(67%) + 384(40%) +512(10%) = 311.68 for 64 water mills is not close to 350.08
In game I get 350.08 (5.47*64) GP from 64 water mills, according to the mouse over text when you look at a water mill "Effective Power: 5.47 (66% Efficiency Lost)"
Either one or both of us are looking at this wrong, or something is just off....
