### ISSUE TITLE
Builder's Wand and Creative Builder's Wand not placing blocks in 1.7.10

### ISSUE THREAD

**Issue by SpeedF12** [rwtema/extrautilities_old_issues#211]
Hey tema,

Not sure if you have seen the builder's wands (either of them) not work with another mod specifically, have been building a 1.7.10 pack and while it never crashes the server every time I try to use the wand the outline effect will appear properly but a right click will not place the blocks.  I loaded up with just extrautilities and everything was fine until I added in the other mods.  

Now I can definitely go through and add mods one by one however just wanted to check first with you to see if there are any inconsistencies, On another note all the same mods were being used in 1.7.2 and the builder's wand worked fine so it seems like this is limited to the changes occurring to the 1.7.10 port.

Again most likely it is being caused by another mod or possibly the auto id's? (Not sure if this would affect the wand either)

If you want a mod listing I can send it over as well,

Thanks as always,

**Comment by SpeedF12** [comment]
Ok, so figured I would try to add/remove mods and it looks like Galactic Craft does something that causes the Builder's wand not to place blocks.  I am going to put issue request over on micdoodle's page, not sure if you chat with him at all, if there is nothing on your side that needs to be changed let me know and close the request,

Thanks for your time!

**Comment by radfast** [comment]
Hi I'm radfast, co-dev of Galacticraft.

The issue has been raised with us as well, however I am not aware of anything Galacticraft is doing to prevent the Builder's Wand from working.  It's kinda hard for us to trouble-shoot these types of issues as Extra Utilities is not open source.

We are actually having reports of all of the following not working when Galacticraft is installed:
- Golden Bag of Holding - right-click it in player inventory does nothing
- Deep Dark Portal - right-click it, does nothing - no dimension transfer
- Watering Can
- and this, the Builder's Wand

https://github.com/micdoodle8/Galacticraft/issues/795
https://github.com/micdoodle8/Galacticraft/issues/779
https://github.com/micdoodle8/Galacticraft/issues/762

Someone suggested it is because of Extra Utilities's fake player?
Please can you let us know your thoughts and we can maybe find a solution together.

For info, Galacticraft makes bytecode transformations to Minecraft/Forge code in a couple of places which cause a newly spawned player to be of class `GCEntityPlayerMP` which extends `EntityPlayerMP`.  I am not aware of this causing problems with any other mod.

**Comment by rwtema** [comment]
Should be fixed in 1.1.0g
