### ISSUE TITLE
Barrel Dupe

### ISSUE THREAD

**Issue by cookta2012** [rwtema/extrautilities_old_issues#22]
well it is with a Extra Utitlies Drum thing and you put one buckket of liquid in the barrel and put it in the liquid transposer from Thermal expansion (while it is set to fill) you switch the mode to extract and sit back and watch

**Comment by TherminatorX** [comment]
Oops, sorry @rwtema . Missed  this when looking for "liquids." Moving pictures and link here for reference. http://tinkers-construct.wikia.com/wiki/Seared_Faucet#comm-9288
![2014-04-23_20 25 54](https://cloud.githubusercontent.com/assets/7256249/2785694/6156bf3a-cb5c-11e3-98b2-242bedab109b.png)
![2014-04-23_20 25 56](https://cloud.githubusercontent.com/assets/7256249/2785695/6159ab5a-cb5c-11e3-986b-c4af70316768.png)
![2014-04-23_20 29 19](https://cloud.githubusercontent.com/assets/7256249/2785696/615c6868-cb5c-11e3-8e32-9d4f9ab3e5af.png)
![2014-04-23_20 29 29](https://cloud.githubusercontent.com/assets/7256249/2785697/615eb320-cb5c-11e3-8b58-2c5be36f6788.png)

**Comment by TherminatorX** [comment]
The comment has been deleted due to wiki policies on cheats. Posting that here for reference:
"don't know if you guys know, but with thermal explasion and extra utilites you can make a liuid infi glitch.....

what you will need

fuiduct/drum/fluid transposer/casting basen/hopper/chest and RF power
simply transfer the liquids into the drum via a smeltary drain and a fluiduct,

place the drum in the fuild fransposer.... you will see it drop into negative number, leave it a while it will jump to about 2.13 billion, from there output it into a castin basen (yellow) and place a hopper hat link to a chest and BOOM

infi metals (this workds with any liquids)

enjoy"

**Comment by rwtema** [comment]
This is a 1.6 Issue. I am no longer developing for 1.6, if this issue is still present in 1.7, please post again.
