### ISSUE TITLE
Crash when placing brick walls

### ISSUE THREAD

**Issue by Mrsuperx13** [rwtema/extrautilities_old_issues#223]
Hi,  I have crashed twice so far after placing a stone brick wall between another two stone brick walls. I do not crash when normally placing the wall but if let's say I missed a block when placing down a row of the walls and i go back to fix it my game crashes. Unfortunately OpenEye is not recognizing it as a crash so i cannot link to the crash report page and there is no crash report in my MC folder either. (I have not tried this with other walls because I didn't want to crash again because MC takes so long to boot up again)
Any help would be greatly appreciated :)
Forge: 99
EU: v 1.1.0f
win 8.1 x64
(Block walls were placed on: Vanilla sandstone)
Thx for making and continuing to uphold EU

**Comment by rwtema** [comment]
Can't replicate. Nothing I can do without a crash log.

**Comment by kryptx** [comment]
Hey, I had this issue too. I think I've narrowed it down to the point that you should be able to reproduce it. However, it might not be your bug to fix.

There's no crash log because it completely locks up the client. Game freezes, java stops responding, close and restart. Yay.

It seems to occur ONLY if CoFH Core is installed. That's in beta state so the issue could very well be with their mod. Plus you obviously don't maintain ForgeMultipart and the issue could be there too. I'm just hoping this will at least get more information so that this can be reported to the right party and fixed.

To reproduce, place a wall (any kind of EU wall, on any surface) where it will connect to two other walls, and _at least one_ of them crosses a chunk border. Simplest way is to create a 2x2 square of walls over a chunk border and it should seize up.

For posterity ... the mods I have loaded:
ForgeMultipart 1.1.0.300 (also tried 297)
CodeChickenCore 1.0.2.9
CodeChickenLib 1.1.1.93
CoFH Core 3.0.0B3 (also tried with Thermal Foundation, and also with that and Thermal Expansion, with the same result)
EU 1.1.0g (also tried 1.1.0f)
NEI 1.0.2.15

Using the latest FML (1201)
It works fine with all of those except CoFH Core.

**Comment by Mrsuperx13** [comment]
I can confirm that i had CoFH Core installed at the time of the crash.

**Comment by rwtema** [comment]
Still not able to replicate. Is there anything in the client/server logs?

**Comment by rwtema** [comment]
Just a shot in the dark but what's your permgen setting?

**Comment by kryptx** [comment]
There is nothing in any log, unfortunately.

I'm using the technic launcher primarily (not sure what permgen settings it used), but when trying to narrow it down I used MultiMC with permgen set to 256MB. 

I'd be happy to continue trying to troubleshoot if there are other steps I can take, including attaching a debugger... though I think I'd need your source to step through it?
