### ISSUE TITLE
Freeze with Spruce Wood Planks Fences

### ISSUE THREAD

**Issue by Lusaphor** [rwtema/extrautilities_old_issues#238]
Whenever I start placing Spruce Wood Planks Fences from Extra Utilities 1.0.1g, and my stack reaches a count of 40 it hard freezes my client, server remains unaffected. Not sure if stack size is the problem or just the fences themselves. Using backup player data fixes it. No errors or info from console to help me understand whats taking place.

**Comment by RViper80** [comment]
I have gotten this as well, with stone multipart walls.  In my case it happened occasionally when I would place one, and it locked me out of my world when I broke one I misplaced.  I had to disable multiparts to get back in.  The freeze happens with Forge 1199, and I tried both 1.0.1f and g, as well as Forge Multipart 297 and 300.  Log file ends right when the client freezes, no error message as Lusaphor stated.

I attempted to reproduce this, alone and with the exact same set of mods I am using, in a new world.  I couldn't get it to freeze up in that new world, so unfortunately this may be hard/impossible to track down.

**Comment by BevoLJ** [comment]
I had this happen to me with the fences and profiled it and found it to be COFH.  (Can see that issue here: https://github.com/BevoTechPack/BevoTechPack/issues/246 ) 

Skyboy suggested for now to disable render sorting in the cofh/client.cfg and that fixed all my issues with this.  Note this only happens on some intel cpus so it is pretty hard to sort out.  If this is the same issue.  It happened to me the moment I placed some ExU walls, and since the profile was all COFH, I never put one and one together until seeing this issue here.  

No clue if my issue really had anything to do with ExU but if so hope that helps!

**Comment by BevoLJ** [comment]
I've confirmed this seems to cause the COFH freeze and by MC Editing out the walls it fixes it.  Here is the COFH issue: https://github.com/CoFH/CoFHCore/issues/37

**Comment by rwtema** [comment]
Not my issue then.
