### ISSUE TITLE
Error rendering creative tab icon(?)

### ISSUE THREAD

**Issue by Skyqula** [rwtema/extrautilities_old_issues#267]
So I found another Extra Utilities config crash :(

Disabling parts of ExU changes the creative config tab icon. Apparently there is a configuration where it crashes. Disabling nothing does not crash. This includes versions 1.1.0g aswell as 1.1.0i and seems to require a certain configuration of mods to be present.

Suggestion: Use a fixed vanilla icon.

Crash Log: http://pastebin.com/q2E49bnQ
Config 1:http://pastebin.com/CgKh3nRg
Config 2: http://pastebin.com/tGaAXWz3
Modlist: http://imgur.com/mzkbSm1

**Comment by theraot** [comment]
I had the same problem. Running MC 1.7.10 with Forge 1.7.10-10.13.0.108

I did narrow the problem to only two mods: extrautilities-1.10k.jar and Mekanism-17.10-7.1.0.92.jar the problem occurs when disabling microblocks (ie: `B:MicroBlocksEnabled=false` - leave the rest of the config as created by default).

After testing I found out that the trigger is the presence of ForgeMultipart which is downloaded automatically as a dependency of Mekanism. Extrautilities alone will not crash in this fashion.

The crash happens when navigating on creative mode to the page where the tab for extrautilities would be created.

Steps to reproduce:
- start a fresh Minecraft 1.7.10 installation
- install forge profile
- add extrautilities-1.10k.jar and Mekanism-17.10-7.1.0.92.jar ^1 to the mods folder
- run minecraft
  - create a world in creative mode - default configuration is generated
    Note: CodeChickenLib and ForgeMultipart get downloaded automatically to /mods/1.7.0
- close the game
- edit ExtraUtilities.cfg with `B:MicroBlocksEnabled=false`
- run the game again
  - open the creative world
  - open the inventory
  - click to go to the second page (the button that looks like this: ">")
    Crash!

^1: you may also place directly ForgeMultipart (and optionally CodeChickenLib - it gets downloaded anyway) that's enough to caus the crash.

Edit: in abstract the crash happens when microblocks is disabled and ForgeMultipart is present.

**Comment by rwtema** [comment]
Disable showMultiblocksTab
