### ISSUE TITLE
BigReactors yellorite generation issue in underdark. Info needed.

### ISSUE THREAD

**Issue by archmon** [rwtema/extrautilities_old_issues#284]
Hi rwtema, just woundering if you can help find out why yellorite is not generating in the underdark.
I have a issue page for the big reactors github with more information: https://github.com/erogenousbeef/BigReactors/issues/315

Basically, seems yellorite is not generating in the underdark and retrogen has already been set.
Using BigReactors-0.4.0rc3 and extrautilities-1.1.0i

erogenousbeef asked about if standard ore generation is intended to run.

Thanks

**Comment by erogenousbeef-zz** [comment]
Yes, to clarify, I'm wondering if the underdark runs standard ore generators, or if it runs its own custom generators only. That is, should I expect my ore generator to run in your underdark dimension?

Further, does your underdark dimension's chunk provider extend `ChunkProviderHell` or `ChunkProviderEnd`? I skip dimensions whose chunk providers inherit from those, so that could also be the issue.

**Comment by rwtema** [comment]
The providor extends ChunkProvidorFlat and uses the GameRegistry.generateWorld() method for ore generation..

**Comment by erogenousbeef-zz** [comment]
Hmm. Is the dimensionID negative? I also have negative dimensionIDs blacklisted by default.

**Comment by archmon** [comment]
If I'm not mistaken, it is the folder DIM-100.  not sure if I can confirm that though, but booting my instance to find out if possible.

**Comment by erogenousbeef-zz** [comment]
Ok, this is my bug then.

**Comment by archmon** [comment]
yes, it's DIM-100 for the underdark
