### ISSUE TITLE
API Error with Refined Relocation

### ISSUE THREAD

**Issue by CascadingDragon** [rwtema/extrautilities_old_issues#290]
I was designing a storage system with Refined Relocation, and I needed to move items out of a RR chest. I attached a item transfer node (though I did have an energy node next to it in my hotbar so I might have placed that..) from the chest to the Wireless Block Extender from RR, and I received this crash error. 

I did try removing EU, but it wouldn't load the world and froze Java, and I can't remove RR because my chests have all my items. 
If I reported this to the wrong author, let me know. 
Thank you very much!

Edit: In a fresh world, the crash happens when the transfer node connects to the Wireless Block Extender. The extender can transfer items, fluid, and energy.

http://pastebin.com/TvE5cLG5

**Comment by rwtema** [comment]
Looks to be a Refinded Location/Buildcraft issue.

I think Refined Location tile entity has an IC2 energy sink visible in it's visible field schema. Thus the Buildcraft MJ API finds it and tries to load it (which since I'm guessing you don't have IC2 installed causes a crash). For the moment, either install IC2, the IC2 API or a mod that contains the API.

Since BC is moving to RF, I'll be removing the MJ energy stuff so it ultimately won't matter in the long run.
