### ISSUE TITLE
Magnum Torch Not Preventing Spawns - 1.1.0k

### ISSUE THREAD

**Issue by kingwersen** [rwtema/extrautilities_old_issues#318]
Been having some mobs spawning in my base where they logically shouldn't have - practically on top of a Magnum Torch - so I decided to test the torch in a world.

![2014-09-20_02 31 44](https://cloud.githubusercontent.com/assets/8841480/4344866/d01d84ea-40a9-11e4-8df5-21b4745791d4.png)

As you can see, it's definitely not preventing mob spawns =(. Is this a known issue? I see it's been reported in an earlier version.

**Comment by XentoniX** [comment]
Maybe i am wrong but doesnt Magnum Torch only prevent spawns on Equal Level and lower?

**Comment by kingwersen** [comment]
In 1.6 it had a 16 block vertical radius. It doesn't say what it's vertical radius is ingame, but I can't find anything to indicate this has changed. If anything, the ingame information implies it has a 64 block vertical radius now.

Regardless, it's not preventing spawns on its own level for me either =P.

**Comment by evenas98** [comment]
it is for me, but it prevents mob spawns from cursed earth

**Comment by rwtema** [comment]
Unable to replicate.

**Comment by kingwersen** [comment]
Never mind, I forgot I had optifine on still. It was causing the problem, and turning it off fixed it. Sorry for the false alarm. I had no idea optifine was that intrusive - I thought it only dealt with visuals, etc.

While we're at it though, could you specify what the y-radius of the torch is now? Is it still 16 blocks like in 1.6? or was it bumped up to 64 as implied in the tooltip? Thanks!

**Comment by JLBShecky** [comment]
The reason that this is happening is because Optifine overwrites SpawnerAnimals class which is responsible for forge generating the LivingSpawnEvent.CheckSpawn event. I don't remember what the obfucated class name is off hand as I am on my laptop at the moment and I don't have a working workspace.

One thing to note is that since mob spawning is done server side, if you are playing on a server then and have optifine installed since it is a client side mod the torch will work. Also worth noting is that this optifine compatibility issue not only messes with the Magnum torch's ability to prevent mobs from spawning but it also messes with the Underdark as it also relies on the same event.

**Comment by rwtema** [comment]
Thanks JLBShecky.

Can't do anything about this.
