### ISSUE TITLE
Server crash with ExtraUtilities

### ISSUE THREAD

**Issue by Devilin-Pixy** [rwtema/extrautilities_old_issues#332]
When ExtraUtilities is installed on my modded server it causes a crash. This does however not happen in SP.
For the server I am using Cauldron for MC 1.7.10 (FML #1207).
Crash seems to try to call client-side code on the server for blocks related to ShadowWorld (1.3.0).
No crash with same modpack without ExtraUtilities.

Crash log: http://pastebin.com/VNk9xrQ2
FML-server log: http://pastebin.com/5xrEa1QS

If this crash is caused by ShadowWorld, let me know and I will report to the developer of SW instead

**Comment by TherminatorX** [comment]
"Serious error calling getRenderType() on block shadowworld:AzuriteRune : Likely cause is client-side code is being called server-side" and"java.lang.NoClassDefFoundError: jajo_11/ShadowWorld/GUI/GuiDiaryEntry"

I might actually know what is going on here. "You will unlock new entries by crafting, picking up items, or just looking at things," from the Shadow world OP. The Shadow World mod is trying to give the player a diary entry, but since the "player" breaking the block that gives the entry is the Ender Quarry, it's trying to give it to the block/world.

How close am I, Tema?

You can probably test this theory by using another quarry and/or a block that is able to break and pick up items from the broken block. If it's just the EQ that has issues w/ this, then EU is to blame. If other stuff does this, blame jajo_11 :)

**Comment by rwtema** [comment]
This is a shadow world bug.

The block "shadowworld:AzuriteRune" makes reference to a ClientProxy class which contains client-side only code. getRengerType() is NOT client-side only and is called by the server on numerous occasions and as such must not contain references to client-side code.
