### ISSUE TITLE
energy pipes 1.7.2 cause crash when you break any

### ISSUE THREAD

**Issue by zpowerup** [rwtema/extrautilities_old_issues#66]
http://pastebin.com/tTc2xT1H
crash log from crash after breaking pipe

**Comment by wrincewind** [comment]
I can confirm this happens when playing with the following mods: CodeChickenCore-1.7.2-1.0.0-universal, extrautilities-1.1.0-prerelease-3, InventoryTweaks-1.58-dev-118, and NotEnoughItems-1.7.2-1.0.1-universal. it happens when you break the pipe with your bare hand, so i presume it happens regardless of tool usage. the pipe is broken when the map is re-loaded, though i got a warning from forge about my world having a corrupted level.dat. 

this also happens when breaking transfer pipes, sorting pipes... presumably every kind of pipe, and also on item transfer nodes, so presumably every kind of node, too. Oh dear.

**Comment by zpowerup** [comment]
forgemultipart was not in the 1.7.2 folder in mods folder once i manually added it in no crash when breaking any of the pipes

**Comment by TherminatorX** [comment]
So, XU could be semi-dependent (maybe unintentionally) on FMP. That would not be good, but would explain a lot.

**Comment by zpowerup** [comment]
it wouldn't be bad if XU detected if fmp is installed so that if it isn't installed it would automatically download latest fmp into the correct folder.

**Comment by TherminatorX** [comment]
I don't think XU should be FMP-dependant at all, you shouldn't need it to do anything. The only issue is with the pipes. (and not having fancy fences and pipe jackets, but that's different kettle of fish)

**Comment by rwtema** [comment]
Should be fixed in Pre5a
