### ISSUE TITLE
[1.7.2 prerelease 4] Crash on startup.

### ISSUE THREAD

**Issue by Xcox123** [rwtema/extrautilities_old_issues#72]
http://paste.ee/p/aRdD3 is the MultiMC log, the problem starts at like 165. I think the problems the Bauble Ring(line 171)

**Comment by InvaderAZ** [comment]
You need to have the Baubles mod from Azanor installed to clear up that error, which I just found that if you have Thaumcraft installed it moves the Baubles mod out of the mods folder and into the mods\1.7.2 folder which will then cause this error since Extra Utils seems to only be looking in the root of the mods folder for it? Not sure exactly how that works.

**Comment by Xcox123** [comment]
Thanks, removed Thaumcraft and removed Baubles and it fixed :)

**Comment by ghost** [comment]
Yep its incompatible with TC atm because TC is moving baubles back to /1.7.2....

**Comment by rwtema** [comment]
Should be fixed in Pre5a
