### ISSUE TITLE
ERR Item with GregTech and ExtraUtilities Installed

### ISSUE THREAD

**Issue by Peach774** [rwtema/extrautilities_old_issues#80]
Whenever I craft anything, a weird artifact is left in the table result. It is called an ERR and if you press r in nei it shows all extrautilities fences. As soon as i close my inventory it disappears.

**Comment by BBoldt** [comment]
I am also experiencing this, it only happens when the latest gregtech and the latest extra utilities are installed.

This effects all crafting methods. The ERR thingy is there as soon as you open a crafting gui as if there was a recipe for it that consists of nothing.

![](http://i.imgur.com/CAQsFIr.png)

![](http://i.imgur.com/VNcnvbn.png)

As the guy said above, when you press the recipe key in NEI it cycles through the extra utilities fences.

![](http://i.imgur.com/0AOMscW.png)

**Comment by rwtema** [comment]
Strange. I'm guessing GregTech is somehow changing the id for the microblocks but I'll look into it.

**Comment by rwtema** [comment]
Okay for some reason, Gregtech is calling the recipe, before FMP has registered its items so my FMP-based recipe marks them as missing (which since fences is just microblocks means an empty recipe). I can fix it on my end easily but it might still be an issue for GT.

**Comment by BBoldt** [comment]
Yep, fixed in PR6. Thank you. I'll leave a message on greg's topic too.
