### ISSUE TITLE
Suggestion: Make trash can link to the last millenium

### ISSUE THREAD

**Issue by Da-Technomancer** [rwtema/extrautilities_old_issues#825]
Could you make it so that any items deleted with a trash can get dropped from the sky in the last millenium. I think it would be neat for people to end up just covering the last millenium in garbage. Also, liquid trash cans should have a chance to place the liquid source block into the dimension, and energy trash cans should cause lightning. Just an idea.

**Comment by KnightMiner** [comment]
Doesn't that defeat the purpose of a trash can? (as lava would be better then) And also: so much lag would be caused, as many people use trash cans for mass item deletion

**Comment by Da-Technomancer** [comment]
Maybe, but then again, maybe not. It could change the purpose of the trash can so that people try to be a little more carefull with it, and think before they use it. Also, it would only cause lag if the last millennium was loaded, and most items would probably fall in the void anyways, so it might not be that laggy at all.

**Comment by KnightMiner** [comment]
If the dimension is unloaded you will now can have hundreds of items waiting to drop into the void, so that just moves the lag to another point.

And "thinking twice" when it comes to features in mod tends to come across as "use another mod's version". In any case, why defer from using an item deleter when vanilla has the exact same thing?
