### ISSUE TITLE
Inventory / Pipe Incompatibility with other mods

### ISSUE THREAD

**Issue by utoc** [rwtema/extrautilities_old_issues#924]
Hello!

I'm currently using ExU extrautils2-1.10-alpha-1.0.0 with FML forge-1.10.2-12.18.0.2008

You can see a demonstration here: http://i.imgur.com/dfWbHKb.png

The following mods do not seem to accept ExU's transfer pipe:

EnderIO
Mekanism
Random Things
TechReborn
Quantum Storage

Other mods seem to work just fine like rfTools, Vanilla, ActuallyAdditions etc.

Let me know if you need any other information.

**Comment by LiftPizzas** [comment]
I also cannot get the indexer to work using EnderIO item pipes. It will take things from the indexer and put them into chests, but the indexer doesn't show any of the items it has sent off to the chests. (I have tried the arrows set in all combinations of directions.)

(I'm using EnderIO pipes because the EU ones are painfully slow when trying to dump an entire inventory into the system.)
