### ISSUE TITLE
[pre7a] Texture issue

### ISSUE THREAD

**Issue by kardain** [rwtema/extrautilities_old_issues#96]
Trading post has a broken texture on the bottom face as it appears it is attempting to call an invalid vanilla texture

```
[12:34:46] [Client thread/ERROR]: Using missing texture, unable to load minecraft:textures/blocks/planks.png
java.io.FileNotFoundException: minecraft:textures/blocks/planks.png
```

**Comment by rwtema** [comment]
Ah yes, this is an old bug that's been in Extra Utilities since the first release, IIRC. At this point I consider it to be an old friend and since It's harmless and not really noticeable I actually won't be fixing it.

If people insist, I'll add a config option for those who are really OCD about these things.

**Comment by kardain** [comment]
Completely understandable about the won't fix and  had no idea that feature has been that way for that long (honestly, how many people actually look at the bottom of blocks).

Anyway, off I go to the next mod tossing that error.

**Comment by TherminatorX** [comment]
I personally don't like missing textures anywhere, and so would be glad to have that as an option.
